#!/bin/bash
#
# Cloudflare Real IP Configuration Script
# Fetches Cloudflare IP ranges and generates nginx configuration
# to properly identify the real client IP behind Cloudflare proxy.
#
# Environment Variables:
#   CLOUDFLARE_REALIP - Set to "true" to enable Cloudflare real IP support
#   CLOUDFLARE_REALIP_HEADER - Custom header name (default: CF-Connecting-IP)
#   CLOUDFLARE_REALIP_RECURSIVE - Enable recursive real IP processing (default: on)
#

set -e

CLOUDFLARE_CONFIG_FILE="/etc/nginx/conf.d/cloudflare_realip.conf"
CLOUDFLARE_IPV4_URL="https://www.cloudflare.com/ips-v4/"
CLOUDFLARE_IPV6_URL="https://www.cloudflare.com/ips-v6/"

# Default values
: ${CLOUDFLARE_REALIP:="false"}
: ${CLOUDFLARE_REALIP_HEADER:="CF-Connecting-IP"}
: ${CLOUDFLARE_REALIP_RECURSIVE:="on"}

generate_cloudflare_realip_config() {
    echo "Fetching Cloudflare IP ranges..."
    
    # Fetch IPv4 ranges
    local ipv4_ranges
    ipv4_ranges=$(curl -s --fail "$CLOUDFLARE_IPV4_URL" 2>/dev/null) || {
        echo "Warning: Failed to fetch Cloudflare IPv4 ranges" >&2
        return 1
    }
    
    # Fetch IPv6 ranges
    local ipv6_ranges
    ipv6_ranges=$(curl -s --fail "$CLOUDFLARE_IPV6_URL" 2>/dev/null) || {
        echo "Warning: Failed to fetch Cloudflare IPv6 ranges" >&2
        return 1
    }
    
    # Validate we got data
    if [[ -z "$ipv4_ranges" ]] || [[ -z "$ipv6_ranges" ]]; then
        echo "Warning: Empty response from Cloudflare IP endpoints" >&2
        return 1
    fi
    
    echo "Generating Cloudflare real IP nginx configuration..."
    
    # Generate the configuration file
    cat > "${CLOUDFLARE_CONFIG_FILE}.tmp" << EOF
# Cloudflare Real IP Configuration
# Auto-generated by cloudflare_realip.sh
# Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
#
# This configuration allows nginx to extract the real client IP
# from the ${CLOUDFLARE_REALIP_HEADER} header when traffic comes through Cloudflare.

# Cloudflare IPv4 ranges
EOF

    # Add IPv4 set_real_ip_from directives
    while IFS= read -r ip; do
        [[ -n "$ip" ]] && echo "set_real_ip_from $ip;" >> "${CLOUDFLARE_CONFIG_FILE}.tmp"
    done <<< "$ipv4_ranges"
    
    echo "" >> "${CLOUDFLARE_CONFIG_FILE}.tmp"
    echo "# Cloudflare IPv6 ranges" >> "${CLOUDFLARE_CONFIG_FILE}.tmp"
    
    # Add IPv6 set_real_ip_from directives
    while IFS= read -r ip; do
        [[ -n "$ip" ]] && echo "set_real_ip_from $ip;" >> "${CLOUDFLARE_CONFIG_FILE}.tmp"
    done <<< "$ipv6_ranges"
    
    # Add real_ip_header directive
    cat >> "${CLOUDFLARE_CONFIG_FILE}.tmp" << EOF

# Use Cloudflare's header to get the real client IP
real_ip_header ${CLOUDFLARE_REALIP_HEADER};

# Enable recursive real IP processing
# This handles cases where the request passes through multiple proxies
real_ip_recursive ${CLOUDFLARE_REALIP_RECURSIVE};
EOF

    # Move temporary file to final location
    mv "${CLOUDFLARE_CONFIG_FILE}.tmp" "$CLOUDFLARE_CONFIG_FILE"
    
    echo "Cloudflare real IP configuration written to $CLOUDFLARE_CONFIG_FILE"
    return 0
}

remove_cloudflare_realip_config() {
    if [[ -f "$CLOUDFLARE_CONFIG_FILE" ]]; then
        rm -f "$CLOUDFLARE_CONFIG_FILE"
        echo "Removed Cloudflare real IP configuration"
    fi
}

# Main execution
main() {
    local action="${1:-setup}"
    
    case "$action" in
        setup)
            if [[ "${CLOUDFLARE_REALIP,,}" == "true" ]] || [[ "${CLOUDFLARE_REALIP}" == "1" ]]; then
                echo "Cloudflare real IP support is enabled"
                generate_cloudflare_realip_config
            else
                echo "Cloudflare real IP support is disabled (set CLOUDFLARE_REALIP=true to enable)"
                remove_cloudflare_realip_config
            fi
            ;;
        update)
            # Force update regardless of CLOUDFLARE_REALIP setting
            # Used for cron updates when the feature is already enabled
            if [[ -f "$CLOUDFLARE_CONFIG_FILE" ]] || [[ "${CLOUDFLARE_REALIP,,}" == "true" ]] || [[ "${CLOUDFLARE_REALIP}" == "1" ]]; then
                generate_cloudflare_realip_config
            fi
            ;;
        remove)
            remove_cloudflare_realip_config
            ;;
        *)
            echo "Usage: $0 [setup|update|remove]"
            echo "  setup  - Generate config if CLOUDFLARE_REALIP is enabled (default)"
            echo "  update - Force update the configuration"
            echo "  remove - Remove the configuration file"
            exit 1
            ;;
    esac
}

main "$@"

